### ISSUE TITLE
"Search" button in the Cert Services tool

### ISSUE THREAD

**Issue by jfuega** [UWIT-IAM/cert-service#39]
User is asking for a "Search" button in the Cert Services tool (https://iam-tools.u.washington.edu/cs/). [REQ7058387](https://uwconnect.uw.edu/now/nav/ui/classic/params/target/u_simple_requests.do%3Fsys_id%3D5c2141b0c3f26910926e19a4e4013148%26sysparm_record_target%3Dtask%26sysparm_record_row%3D1%26sysparm_record_rows%3D11%26sysparm_record_list%3Dassignment_group%253De3a94c2e6fb0250079d3fd16ad3ee437%255EORassignment_group%253D960356e26f26110054aafd16ad3ee46d%255EORassignment_group%253D9a0356e26f26110054aafd16ad3ee46f%255EORassignment_group%253Dae0356e26f26110054aafd16ad3ee471%255EORassignment_group%253D83e2d2e26f26110054aafd16ad3ee483%255EORassignment_group%253D83d36a1a6fd1210090ead2054b3ee4cd%255EORassignment_group%253D1c1356e26f26110054aafd16ad3ee489%255EORassignment_group%253D14b292e26f26110054aafd16ad3ee4a6%255EORassignment_group%253Daad9503adb8af38437ae9ec6db96197c%255EORassignment_group%253Dcdf9d058db14d454467117e15b96199a%255EORsys_class_name%253Dpm_project%255Eassigned_toDYNAMIC90d1921e5f510100a9ad2572f2b477fe%255EORref_pm_project.project_managerDYNAMIC90d1921e5f510100a9ad2572f2b477fe%255EstateNOT%2BIN6%252C7%255Eactive%253Dtrue%255Esys_class_name%2521%253Duniversal_request%255EORDERBYstate%255EORDERBYsys_updated_on%255EORDERBYpriority%255EORDERBYsys_created_on)

**Comment by stea-uw** [comment]
I'll take this task to get a feel for the code review process.

**Comment by stea-uw** [comment]
Before I got started, I added some basic automation to the repo. I added a build test and an optional pre-commit hook to verify the project builds.

https://github.com/UWIT-IAM/cert-service/pull/55
https://github.com/UWIT-IAM/cert-service/pull/56

Hopefully this distraction will pay off in the long-term in the form of faster and safer reviews.

**Comment by stea-uw** [comment]
https://github.com/UWIT-IAM/cert-service/pull/59 to fix the actual issue.

**Comment by chmc3** [comment]
Would this be a release of the cert services software? I'd assume so but want to confirm. If so, we should look at the other "small" enhancements we have in our backlog/to review and see if we can easily bundle a QoL release of features.

**Comment by stea-uw** [comment]
Yup, this would be a small release.

While we can bundle some things in, one of the goals of this release was to increase the safety and convenience of the release process, so hopefully we don't need to worry as much about bundling things in the future 🤞

**Comment by chmc3** [comment]
Happy to be able to do small releases as well! It would help me to have experience with our "change" process to do minor ones. Let's not do this as a bundle as a result.

**Comment by chmc3** [comment]
Created CHG0046744 for the release

**Comment by stea-uw** [comment]
Fixed by recent prod push of latest changes
