### ISSUE TITLE
Update Diafines 6-12 to run win-acme 

### ISSUE THREAD

**Issue by chmc3** [UWIT-IAM/cert-service#40]
Currently Diafines 6-12 run certbot to install certificates via ACME. In order to get more experience with win-acme and decrease the need to "install" the new certificate each year, win-acme should be configured and run. Once tested, the certbot connection should be removed.

**Comment by chmc3** [comment]
@jprosser Tagging you in on this one! My account seems to have some errors with running certbot and can't run winacme. 

Could you either: 

- [ ] troubleshoot win-acme and configure it to auto-renew and install the cert in ISS (steps at https://wiki.cac.washington.edu/display/infra/Using+ACME+for+Certificate+Management) 
- [ ] Determine that win-acme can't be made to work in the Diafine environment and update the cert in ISS to use the new one manually (not my favorite option)
- [ ] Fix whatever the heck is up with my account and punt this back to me to do

Thanks!
Colin

**Comment by jprosser** [comment]
Just noting that it took a reboot of each to get the networking stack back.  The odd behavior was seem where in various browsers (firefox, ie, chrome) some web sites were not reachable and some most downloads wouldn't actually complete 100%.  Rebooting fixed that/those networking issue(s) which was seen on every single diafine.  That leads me to believe that at the very least these servers need to be rebooted on a regular basis if not flipped to only run occasionally with automation.  I would hazard a guess your account is maybe fine after all these reboots.
