### ISSUE TITLE
Automate DCV process with API calls

### ISSUE THREAD

**Issue by chmc3** [UWIT-IAM/cert-service#47]
Domain Control Validation is currently a fully manual process that is done by specialists. Upcoming changes by the CA/B have indicated that DCV is likely to move to needing to be renewed every 90 days to match the lifespan of SSL/TLS certificates. 

For domains in the UW DNS, this is done via generating a CNAME record in Sectigo and placing it in the UW DNS. 
For domains not in the UW DNS, this is done by requesting the domain contact place the CNAME record in their DNS system.

Since both Sectigo and the UW DNS have API's that the services should be able to utilize, there appears to be an opportunity to automate this process and decrease the manual effort.

**Comment by chmc3** [comment]
The process for doing DCV can be found in documentation on [the wiki.](https://wiki.cac.washington.edu/display/SMW/DCV+Expiration+Processing) A video walkthrough of this can be found at [the recorded trainings](https://drive.google.com/file/d/1ORHwZYy7_1W3Ec43ABBWe7bx3-LTUKAU/view?usp=drive_link) and a demonstration of how it's currently manually done can be found [there as well.](https://drive.google.com/file/d/1bEtibBt9wUDDzI7aw_bwg9O5GP3HooQB/view?usp=drive_link)

@soufianerafik had dome some preliminary work exploring this, and may be more familiar with the [networks API](https://networks.uw.edu/networks/apidocs)

**Comment by stea-uw** [comment]
Thanks Colin! I'd be happy to look into this. Could you and/or Andrew help jumpstart the process with a few questions?

1. Do you know where the existing alert job that files the UW connect issues is? If not, could you link me an example issue in UW connect?
2. How often do you get these alerts?
3. Are there any existing web dashboards for this?
4. Do you know if the team currently has any batch jobs or background tasks that use the new deployment process (Flux)?

**Comment by chmc3** [comment]
1. Currently we take notifications in the form of emails, like in [REQ7791752](https://uw.service-now.com/now/nav/ui/classic/params/target/u_simple_requests.do%3Fsys_id%3D0404c6c0c36af11426a0300f05013144%26sysparm_record_target%3Dtask%26sysparm_record_row%3D1%26sysparm_record_rows%3D35%26sysparm_record_list%3Dassignment_group%253De3a94c2e6fb0250079d3fd16ad3ee437%255EORassignment_group%253D960356e26f26110054aafd16ad3ee46d%255EORassignment_group%253D9a0356e26f26110054aafd16ad3ee46f%255EORassignment_group%253Dae0356e26f26110054aafd16ad3ee471%255EORassignment_group%253D83e2d2e26f26110054aafd16ad3ee483%255EORassignment_group%253D83d36a1a6fd1210090ead2054b3ee4cd%255EORassignment_group%253D1c1356e26f26110054aafd16ad3ee489%255EORassignment_group%253D14b292e26f26110054aafd16ad3ee4a6%255EORassignment_group%253Daad9503adb8af38437ae9ec6db96197c%255EORassignment_group%253Dcdf9d058db14d454467117e15b96199a%255Esys_created_on%253E%253Djavascript%253Ags.beginningOfLastMonth%2528%2529%255Eu_caller%253D7cfc9bad6fa02500ab448bec5d3ee43f%255Esys_class_name%2521%253Duniversal_request%255EORDERBYpriority%255EORDERBYDESCsys_updated_on%255EORDERBYstate%255EORDERBYDESCsys_created_on). My understanding is we may also be able to get the information out of the Sectigo API because processing email isn't great as an input method. 
2. Daily alerts, it alerts any domain who's DCV is going to expire in the next 30 days. Once a domain has DCV renewed, it falls off the alert. 
3. The alerts appear in the IAM Dashboard in UW Connect under the tab "IAM-DCV"
4. Out of my league on this one. 
I will warn that the hardest part of this will be that some domains are in the UW DNS and thus can be automatically renewed, and some domains are not so require a customer to make the update. But that should be determinable by the Networks API so you would have one set of behavior for domains that don't have a UW DNS record and an automatic update for those that do.

**Comment by stea-uw** [comment]
Awesome, thanks! On last question::

Do we maintain a mapping from certificate to owner? We can email the non-UW DNS people directly rather than going through specialists.

**Comment by chmc3** [comment]
Yes, largely. We have records of who requested a cert for that domain, and we have who has permissions to request certs for that domain. For external contacting we have been using the latter, emailing all of those that
In the database behind /cs we have a record

**Comment by chmc3** [comment]
@stea-uw 
I was going to ask you about this in the team meeting, but I should be better about using our tools! Can I get an update on what work is left to do and if there is anything I can help do and unblock?

**Comment by stea-uw** [comment]
Good question! It's code complete but not pushed.

Right now, I'm running it on my box while I wait for PR https://github.com/UWIT-IAM/gcp-k8/pull/190 to get this fully automated in kubernetes.

**Comment by stea-uw** [comment]
This is now done and running in prod without errors
